        services:
          campusmgmtsystem:
            image: your-dockerhub-username/your-app-image:latest   # replace with your app image
            container_name: campus_app
            ports:
              - "7079:8080"
            depends_on:
              - mongodb
            environment:
                    MONGO_URL: "mongodb://mongodb:27017/campusdb"

          mongodb:
            image: mongo:6.0
            container_name: campus_mongo
            restart: always
            ports:
              - "27017:27017"
            volumes:
              - mongo_data:/data/db

        mysql:
            image: mysql:8
            container_name: mysql-container
            environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            ports:
              - "3306:3306"
            volumes:
              - mysql_data:/var/lib/mysql

        volumes:
          mongo_data:
        volumes:
          mysql_data:
